# Build settings
remote_theme: fongandrew/hydeout
markdown: kramdown

title:            Adam Thomas Cole
tagline:          'Classical Composition'
description:      'Classical Composition'
url:              https://adamthomascole.github.io

paginate:   5

# Sidebar link settings
sidebar_home_link:  true

#added by IC
sidebar_photo_url: '/images/adam_fancy_pants_300x480_ACK.png'
