# Build settings
remote_theme: fongandrew/hydeout
markdown: kramdown

title:            Adam Thomas Cole
tagline:          'Classical Composition'
description:      'This is my description!'
url:              https://adamthomascole.github.io

paginate:   5

# Sidebar link settings
sidebar_home_link:  true
